
import { Inter } from "next/font/google";
import "./globals.css";
// import { UserProvider } from "@auth0/nextjs-auth0"
import Navbar from "./components/navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Glopix:Revolutionize your pixel",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
     <UserProvider>
     <body className={inter.className}>
        <Navbar/>
          {children}
          </body>
     </UserProvider>
        
        
        
    </html>
    
  );
}
